name: Update Printers

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes

  workflow_dispatch:  # Allows manual trigger

jobs:
  update-printers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version to use

    - name: Install dependencies in doc_script folder
      run: |
        cd doc_update_script  # Change to the doc_script folder
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure this file is in the doc_script folder

    - name: Run the script to update printers
      run: |
        cd doc_update_script  # Change to the doc_script folder
        python copy-printer-files.py  # Adjust path if necessary

    - name: Check for file changes and commit if needed
      run: |
        cd doc_update_script
        git config --global user.name "infill bot"
        git config --global user.email "github-actions@github.com"

        # Get list of changed files (comma-separated)
        CHANGED_FILES=$(git diff --name-only | tr '\n' ', ' | sed 's/, $//')

        git add -A
        git diff --cached --exit-code || (
          if [ -z "$CHANGED_FILES" ]; then
            git commit -m "Auto update printer files"
          else
            git commit -m "Auto update printer files. Modified: $CHANGED_FILES"
          fi &&
          git push origin main
        )